---
title: "Homework 11"
author: "Mia Murphy"
date: "5/19/2021"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r, warning = FALSE}


## Data Setup

## Set seed
set.seed(100)

## Read in CSV
moose1 <- read.csv('moose1.csv')


# Summary
summary(moose1)


```

```{r}

## Standard Dev
cranial_sd <- sd(moose1$Cranialvolume)
abundance_sd <- sd(moose1$Mooseabundance)

## Means
cranial_mean <- mean(moose1$Cranialvolume)
abundance_mean <- mean(moose1$Mooseabundance)

## Dimensions
obs <- nrow(moose1)
obs

```

```{r, warning = FALSE}


##################################################
# function: FileBuilder
# create a set of random files for regression
# input: fileN = number of files to create
#       : fileFolder = name of folder for random files
#       : fileSize = c(min,max) number of rows in file
#       : fileNA = number on average of NA values per column
# output: set of random files
#------------------------------------------------- 
FileBuilder <- function(fileN=10,
                        fileFolder="moosedata/",
                        fileSize=c(15,100),
                        fileNA=3){
for (i in seq_len(fileN)) {
fileLength <- sample(fileSize[1]:fileSize[2],size=1) # get number of rows
Cranialvolume <- rnorm(n= obs, mean = cranial_mean, sd = cranial_sd) ## Create random Y values based on vector
Mooseabundance <- rnorm(n = obs, mean = abundance_mean, sd = abundance_sd) ## Create random X values based on vector
dF <- data.frame(Cranialvolume, Mooseabundance) # bind into a data frame

# create label for file name with padded zeroes
fileLabel <- paste(fileFolder,
                       "moose_batch",
                       formatC(i,
                       width=3,
                       format="d",
                       flag="0"),
                       ".csv",sep="")

# set up data file and incorporate time stamp and minimal metadata
write.table(cat("# Simulated moose data file for batch processing","\n",
                    "# timestamp: ",as.character(Sys.time()),"\n",
                    "# MM","\n",
                    "# ------------------------", "\n",
                    "\n",
                    file=fileLabel,
                    row.names="",
                    col.names="",
                    sep=""))

# now add the data frame
write.table(x=dF,
            file=fileLabel,
            sep=",",
            row.names=FALSE,
            append=TRUE)


}
}


```


```{r, warning=FALSE}

##################################################
# function: regStats
# fits linear model, extracts statistics
# input: 2-column data frame (x and y)
# output: slope, p-value, and r2
#------------------------------------------------- 
regStats <- function(d=NULL) {
             if(is.null(d)) {
               cranial_x <- runif(100)
               abundance_y <- runif(100)
               d <- data.frame(Cranialvolume, Mooseabundance)
             }
  . <- lm(data=d,d[,2]~d[,1])
  . <- summary(.)
  statsList <- list(Slope=.$coefficients[2,1],
                    pVal=.$coefficients[2,4],
                    r2=.$r.squared)
  return(statsList)

}

```

```{r, warning=FALSE}
########
#--------------------------------------------
# Global variables
fileFolder <- "moosedata/"
nFiles <- 5
fileOut <- "StatsSummary.csv"
#--------------------------------------------

# Create 100 random data sets
dir.create(fileFolder)
FileBuilder(fileN=nFiles)

```

```{r}
fileNames <- list.files(path=fileFolder)

# Create data frame to hold file summary statistics
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA,nFiles)
pVal <- rep(NA,nFiles)
r2 <- rep(NA,nFiles)

statsOut <- data.frame(ID,fileName,slope,pVal,r2)

# batch process by looping through individual files
for (i in seq_along(fileNames)) {
  data <- read.table(file=paste(fileFolder,fileNames[i],sep=""),
                     sep=",",
                     header=TRUE) # read in next data file
  
  dClean <- data[complete.cases(data),] # get clean cases
  
  . <- regStats(dClean) # pull regression stats from clean file
  statsOut[i,3:5] <- unlist(.) # unlist, copy into last 3 columns
  
}
# set up output file and incorporate time stamp and minimal metadata
  write.table(cat("# Summary stats for ",
                    "batch processing of regression models","\n",
                    "# timestamp: ",as.character(Sys.time()),"\n",
                    "# MM","\n",
                    "# ------------------------", "\n",
                    "\n",
                    file=fileOut,
                    row.names="",
                    col.names="",
                    sep=""))

```

```{r, warning = FALSE}

# now add the data frame
  write.table(x=statsOut,
              file=fileOut,
              row.names=FALSE,
              col.names=TRUE,
              sep=",",
              append=TRUE)
  
print(statsOut)

```


